In [3]:
import pandas as pd
import numpy as np
import requests as req

In [4]:
nyse = pd.read_csv("Pricing Time Series.csv")

In [5]:
nyse.drop("Unnamed: 0", axis =1, inplace =True)
nyse

              Date Ticker   Volume  Weekly Close  Weekly Open
0       2018-01-17    MRC  1253985         18.66        19.00
1       2018-01-12    MRC  2874104         18.98        17.55
2       2018-01-05    MRC  2048120         17.59        17.01
3       2017-12-29    MRC  1252696         16.92        16.63
4       2017-12-22    MRC  2893492         16.59        16.23
5       2017-12-15    MRC  4591590         15.98        15.81
6       2017-12-08    MRC  7329330         15.82        16.22
7       2017-12-01    MRC  6579225         16.08        15.33
8       2017-11-24    MRC  3511448         15.35        14.93
9       2017-11-17    MRC  5198272         14.82        15.66
10      2017-11-10    MRC  5603685         15.77        16.36
11      2017-11-03    MRC  5335432         16.58        16.93
12      2017-10-27    MRC  1940151         16.97        17.75
13      2017-10-20    MRC  1894914         17.74        18.40
14      2017-10-13    MRC  2194543         18.23        17.91
15      2017-10-06    MRC  2409110         17.86        17.32
16      2017-09-29    MRC  5227335         17.49        17.25
17      2017-09-22    MRC  2950643         17.19        17.09
18      2017-09-15    MRC  3244392         16.98        16.68
19      2017-09-08    MRC  1893117         16.61        16.08
20      2017-09-01    MRC  2485910         16.04        15.95
21      2017-08-25    MRC  2883903         15.88        15.63
22      2017-08-18    MRC  4039713         15.63        15.90
23      2017-08-11    MRC  4287870         15.71        15.98
24      2017-08-04    MRC  8076932         16.10        16.32
25      2017-07-28    MRC  4250263         16.27        16.23
26      2017-07-21    MRC  3770738         16.18        16.99
27      2017-07-14    MRC  6924968         17.06        15.90
28      2017-07-07    MRC  2258628         16.07        16.63
29      2017-06-30    MRC  4423238         16.52        15.33
...            ...    ...      ...           ...          ...
259657  2000-08-04    WPC    52600         17.00        17.31
259658  2000-07-28    WPC    61600         17.19        17.44
259659  2000-07-21    WPC    92500         17.56        16.69
259660  2000-07-14    WPC    96900         16.69        16.88
259661  2000-07-07    WPC    63400         16.88        16.56
259662  2000-06-30    WPC   131400         16.38        17.00
259663  2000-06-23    WPC    58700         16.88        17.00
259664  2000-06-16    WPC   130200         16.88        16.94
259665  2000-06-09    WPC    76500         16.94        16.94
259666  2000-06-02    WPC    64000         16.75        16.75
259667  2000-05-26    WPC    81600         16.75        17.19
259668  2000-05-19    WPC    83500         17.06        17.81
259669  2000-05-12    WPC    79600         17.75        18.00
259670  2000-05-05    WPC    95000         18.19        17.88
259671  2000-04-28    WPC   129500         17.88        17.00
259672  2000-04-20    WPC   123600         17.19        17.00
259673  2000-04-14    WPC   168000         16.75        16.81
259674  2000-04-07    WPC   131500         16.88        16.62
259675  2000-03-31    WPC   144600         16.62        17.06
259676  2000-03-24    WPC   156800         17.25        17.00
259677  2000-03-17    WPC   175500         16.94        17.00
259678  2000-03-10    WPC   119400         17.06        17.25
259679  2000-03-03    WPC   112300         17.25        17.69
259680  2000-02-25    WPC   134500         17.50        16.50
259681  2000-02-18    WPC   146800         16.69        16.81
259682  2000-02-11    WPC   131000         16.94        16.44
259683  2000-02-04    WPC   123900         16.62        16.44
259684  2000-01-28    WPC   134700         16.50        17.25
259685  2000-01-21    WPC   190100         17.31        16.69
259686  2000-01-14    WPC   129200         16.50        16.25

[259687 rows x 5 columns]

In [6]:
date =[] 
open_price =[]
close_price = []
ticker = []
volume =[]

for index, row in nyse.iterrows():
    start = row["Weekly Open"]
    end = row["Weekly Close"]
    ten_perc = (start*.1)
    if((start-end)>=ten_perc):
        date.append(row["Date"])
        open_price.append(start)
        close_price.append(end)
        ticker.append(row["Ticker"])
        volume.append(row["Volume"])

In [7]:
df = pd.DataFrame({
    "Opening Price":open_price,
    "Closing Price":close_price,
    "Ticker":ticker,
    "Date":date
})
drops = df[["Ticker","Opening Price","Closing Price","Date"]]
drops

     Ticker  Opening Price  Closing Price        Date
0       MRC         17.340         15.290  2017-06-23
1       MRC         10.080          8.940  2016-02-12
2       MRC         12.780         11.380  2016-01-08
3       MRC         12.840         11.350  2015-08-21
4       MRC         14.980         13.220  2015-07-24
5       MRC         13.910         12.340  2015-01-16
6       MRC         17.020         14.170  2014-12-12
7       MRC         20.050         17.160  2014-12-05
8       MRC         29.400         25.010  2014-02-21
9       MRC         27.140         24.170  2013-08-02
10      MRC         33.150         28.390  2013-05-31
11      NVG         11.000          9.830  2008-12-05
12      NVG         11.170          9.970  2008-11-21
13      NVG         10.800          8.350  2008-10-10
14      TDY         36.970         29.490  2009-01-23
15      TDY         41.600         37.380  2009-01-16
16      TDY         53.000         42.800  2008-10-10
17      TDY         30.550         27.200  2005-04-15
18      TDY         14.950         13.360  2003-01-24
19      TDY         17.600         15.350  2002-10-11
20      TDY         16.750         14.910  2002-07-19
21      TDY         16.760         14.610  2001-06-22
22      TDY         20.120         14.300  2001-02-23
23      TDY         23.250         18.440  2001-01-05
24      TDY         22.560         19.940  2000-12-22
25      TDY         24.500         19.750  2000-12-01
26      TDY         26.500         23.750  2000-11-10
27      TDY         28.130         23.000  2000-10-27
28      TDY         29.000         23.440  2000-10-06
29      TDY         28.880         25.560  2000-09-22
...     ...            ...            ...         ...
7177    PAR          7.750          6.620  2008-01-04
7178    PAR          9.080          7.590  2006-10-06
7179    PAR         10.090          8.880  2006-09-08
7180    PAR         10.670          8.340  2006-07-28
7181    PAR         14.700         12.990  2006-06-09
7182    PAR         17.070         15.360  2006-05-12
7183    PAR         19.850         17.690  2006-02-24
7184    PAR         21.790         19.390  2006-02-10
7185    PAR         32.110         28.020  2005-12-16
7186    PAR         29.850         24.770  2005-08-19
7187    PAR         34.010         29.980  2005-08-05
7188    PAR         37.900         34.000  2005-07-29
7189    PAR         33.360         29.450  2005-06-24
7190    PAR         12.250         10.480  2004-04-16
7191    PAR          5.350          4.670  2002-09-27
7192    PAR          3.550          2.950  2002-02-08
7193    PAR          3.900          3.500  2001-08-24
7194    PAR          3.850          3.350  2001-06-22
7195    PAR          2.100          1.850  2001-03-30
7196    PAR          2.450          2.100  2001-02-23
7197    PAR          2.438          2.125  2000-12-08
7198    PAR          2.875          2.500  2000-10-20
7199    PAR          3.438          3.063  2000-08-11
7200    PAR          4.250          3.500  2000-07-21
7201    PAR          4.750          4.250  2000-07-14
7202    PAR          5.063          4.313  2000-03-31
7203    WPC         23.230         20.200  2008-10-24
7204    WPC         24.000         18.860  2008-10-10
7205    WPC         33.150         29.020  2003-08-01
7206    WPC         20.990         18.500  2001-06-29

[7207 rows x 4 columns]

In [8]:
drops["Ticker"].count()

7207

In [9]:
drops.to_csv("price drop.csv", index=False)