In [1]:
import pandas as pd
import numpy as np
import requests as req
import winsound

In [2]:
timeseries = pd.read_csv("Pricing Time Series.csv")

In [3]:
pricedrop = pd.read_csv("price drops.csv")

In [4]:
# timeseries.drop("Unnamed: 0", axis=1, inplace=True)
# pricedrop.drop("Unnamed: 0", axis=1, inplace=True)

In [5]:
timeseries.head()

   Unnamed: 0        Date Ticker   Volume  Weekly Close  Weekly Open
0           0  2018-01-17    MRC  1253985         18.66        19.00
1           1  2018-01-12    MRC  2874104         18.98        17.55
2           2  2018-01-05    MRC  2048120         17.59        17.01
3           3  2017-12-29    MRC  1252696         16.92        16.63
4           4  2017-12-22    MRC  2893492         16.59        16.23

In [6]:
timeseries["Date"] = timeseries["Date"].str.replace('-','')
timeseries["Date"] = timeseries["Date"].apply(pd.to_numeric, errors='coerce')

In [7]:
timeseries.head()

   Unnamed: 0      Date Ticker   Volume  Weekly Close  Weekly Open
0           0  20180117    MRC  1253985         18.66        19.00
1           1  20180112    MRC  2874104         18.98        17.55
2           2  20180105    MRC  2048120         17.59        17.01
3           3  20171229    MRC  1252696         16.92        16.63
4           4  20171222    MRC  2893492         16.59        16.23

In [8]:
timeseries = timeseries[timeseries['Date'] > 20079999]

In [9]:
timeseries

        Unnamed: 0      Date Ticker   Volume  Weekly Close  Weekly Open
0                0  20180117    MRC  1253985        18.660        19.00
1                1  20180112    MRC  2874104        18.980        17.55
2                2  20180105    MRC  2048120        17.590        17.01
3                3  20171229    MRC  1252696        16.920        16.63
4                4  20171222    MRC  2893492        16.590        16.23
5                5  20171215    MRC  4591590        15.980        15.81
6                6  20171208    MRC  7329330        15.820        16.22
7                7  20171201    MRC  6579225        16.080        15.33
8                8  20171124    MRC  3511448        15.350        14.93
9                9  20171117    MRC  5198272        14.820        15.66
10              10  20171110    MRC  5603685        15.770        16.36
11              11  20171103    MRC  5335432        16.580        16.93
12              12  20171027    MRC  1940151        16.970        17.75
13              13  20171020    MRC  1894914        17.740        18.40
14              14  20171013    MRC  2194543        18.230        17.91
15              15  20171006    MRC  2409110        17.860        17.32
16              16  20170929    MRC  5227335        17.490        17.25
17              17  20170922    MRC  2950643        17.190        17.09
18              18  20170915    MRC  3244392        16.980        16.68
19              19  20170908    MRC  1893117        16.610        16.08
20              20  20170901    MRC  2485910        16.040        15.95
21              21  20170825    MRC  2883903        15.880        15.63
22              22  20170818    MRC  4039713        15.630        15.90
23              23  20170811    MRC  4287870        15.710        15.98
24              24  20170804    MRC  8076932        16.100        16.32
25              25  20170728    MRC  4250263        16.270        16.23
26              26  20170721    MRC  3770738        16.180        16.99
27              27  20170714    MRC  6924968        17.060        15.90
28              28  20170707    MRC  2258628        16.070        16.63
29              29  20170630    MRC  4423238        16.520        15.33
...            ...       ...    ...      ...           ...          ...
259241      259241  20080725    WPC   132401        28.820        29.08
259242      259242  20080718    WPC   170535        28.730        28.06
259243      259243  20080711    WPC   189063        27.250        27.42
259244      259244  20080703    WPC   116418        27.550        28.90
259245      259245  20080627    WPC   141170        28.720        30.15
259246      259246  20080620    WPC   293957        29.880        31.96
259247      259247  20080613    WPC   213723        31.997        32.50
259248      259248  20080606    WPC   251960        32.290        32.49
259249      259249  20080530    WPC   179698        32.350        31.65
259250      259250  20080523    WPC   219218        31.470        30.99
259251      259251  20080516    WPC   213912        30.860        30.10
259252      259252  20080509    WPC   182456        30.000        30.70
259253      259253  20080502    WPC   208405        30.550        29.96
259254      259254  20080425    WPC   211680        29.920        28.47
259255      259255  20080418    WPC   220114        28.390        28.01
259256      259256  20080411    WPC   129005        28.010        30.00
259257      259257  20080404    WPC   189678        30.000        29.84
259258      259258  20080328    WPC   181100        29.950        30.50
259259      259259  20080320    WPC   270400        30.710        28.98
259260      259260  20080314    WPC   404950        30.860        29.84
259261      259261  20080307    WPC   605937        29.910        32.22
259262      259262  20080229    WPC   423100        32.510        32.20
259263      259263  20080222    WPC    79145        32.300        32.45
259264      259264  20080215    WPC   117913        32.150        32.53
259265      259265  20080208    WPC   132700        32.240        33.70
259266      259266  20080201    WPC   214143        34.000        30.90
259267      259267  20080125    WPC   272800        30.330        28.43
259268      259268  20080118    WPC   324020        29.600        32.85
259269      259269  20080111    WPC   202144        32.110        32.55
259270      259270  20080104    WPC   145200        32.510        32.65

[176996 rows x 6 columns]

In [10]:
pricedrop.head()

   Unnamed: 0 Ticker  Opening Price  Closing Price        Date
0           0    MRC          17.34          15.29  2017-06-23
1           1    MRC          10.08           8.94  2016-02-12
2           2    MRC          12.78          11.38  2016-01-08
3           3    MRC          12.84          11.35  2015-08-21
4           4    MRC          14.98          13.22  2015-07-24

In [11]:
pricedrop["Date"] = pricedrop["Date"].str.replace('-','')
pricedrop["Date"] = pricedrop["Date"].apply(pd.to_numeric, errors='coerce')

In [12]:
pricedrop = pricedrop[pricedrop['Date'] > 20079999]
len(pricedrop)

5453

In [ ]:
index_values=[]
counter = 0
ticker = []

for index, row in pricedrop.iterrows():
    dropdate=row["Date"]
    droptick=row["Ticker"]
    counter = counter+1
    print(counter)
    droplist = timeseries[(timeseries["Ticker"]==droptick)]
    for index, line in droplist.iterrows():
        if (dropdate == line["Date"]):
            ticker.append(line["Ticker"])
            index_values.append(line["Unnamed: 0"])
import winsound
duration = 1000  # millisecond
freq = 440  # Hz
winsound.Beep(freq, duration)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493

In [ ]:
index_df = pd.DataFrame({
    "Ticker": ticker,
    "Index": index_values
})

In [ ]:
index_df

In [ ]:
len(index_df)

In [ ]:
cur = 0
prev = 0
for index, row in index_df:
    cur = row["Index"]
    if((cur - prev)<=4):
        index_df.drop(index)
    prev = cur

In [ ]:
len(index_df)
import winsound
duration = 1000  # millisecond
freq = 440  # Hz
winsound.Beep(freq, duration)

In [49]:
op = []
cl = []
da = []
ti = []
vo = []

counter = 0
for item in index_values:
    counter = counter +1
    print(counter)
    prev = item - 26 
#     fut = item + 26
#     for index, row in pricedrop.iterrows():
#         droptick=row["Ticker"]
#         droplist = timeseries[(timeseries["Ticker"]==droptick)]
    for index, row in timeseries.iterrows():
        for x in range(prev, item):
            if(row["Unnamed: 0"] == x):
                op.append(row["Weekly Open"])
                cl.append(row["Weekly Close"])
                da.append(row["Date"])
                ti.append(row["Ticker"])
                vo.append(row["Volume"])

1

KeyboardInterrupt: